use_frameworks!

target 'HSPodDemo_Example' do
  pod 'HSPodDemo', :path => '../'

  target 'HSPodDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
